/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class thedarkdnktv_openbjs_client_ConsoleLoader */

#ifndef _Included_thedarkdnktv_openbjs_client_ConsoleLoader
#define _Included_thedarkdnktv_openbjs_client_ConsoleLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     thedarkdnktv_openbjs_client_ConsoleLoader
 * Method:    allocConsole
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_thedarkdnktv_openbjs_client_ConsoleLoader_allocConsole
  (JNIEnv *, jobject);

/*
 * Class:     thedarkdnktv_openbjs_client_ConsoleLoader
 * Method:    write
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_thedarkdnktv_openbjs_client_ConsoleLoader_write
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
